import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Marquee from "@/components/shared/Marquee";
import { ToastContainer } from "react-toastify";

const notoSerifBangali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBangali.className} h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <Navbar></Navbar>
        <Marquee></Marquee>
        <main className="flex-1">{children}</main>
        <Footer></Footer>
        <ToastContainer />
      </body>
    </html>
  );
}
